spring.application.name=E-Commerce
spring.datasource.url=jdbc:postgresql://localhost:5432/Demo
spring.datasource.username=postgres
spring.datasource.password=test123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false